// Catalogo cerrado de error codes del MVP (ARCHITECTURE.md lineas 472-507).
//
// Lista finita y estable. Cada code referencia un error reproducible del
// dominio o de la infraestructura. NO inventar codes ad-hoc desde el codigo:
// si necesitas uno nuevo, agregalo aqui con commit explicito documentando
// el caso de uso.
//
// Convencion: los codes se usan con AppError o subclase, ej.:
//   new ValidationError(ErrorCodes.VALIDATION_FAILED, "Email invalido")
//
// Frontend mapea code -> mensaje user-friendly cuando aplica (ver
// components de UI para casos con texto custom).

export const ErrorCodes = {
  // Auth (handled por AuthenticationError, 401)
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",

  // Authorization (handled por AuthorizationError, 403)
  AUTHZ_ROLE_REQUIRED: "AUTHZ_ROLE_REQUIRED",
  AUTHZ_NOT_OWNER: "AUTHZ_NOT_OWNER",
  AUTHZ_CANNOT_GRADE: "AUTHZ_CANNOT_GRADE",
  AUTHZ_CANNOT_MARK_LESSON: "AUTHZ_CANNOT_MARK_LESSON",
  AUTHZ_CANNOT_SUBMIT_ASSIGNMENT: "AUTHZ_CANNOT_SUBMIT_ASSIGNMENT",

  // Assignments (DomainError o NotFoundError)
  ASSIGNMENT_NOT_FOUND: "ASSIGNMENT_NOT_FOUND",
  ASSIGNMENT_TYPE_MISMATCH: "ASSIGNMENT_TYPE_MISMATCH",
  SUBMISSION_NOT_FOUND: "SUBMISSION_NOT_FOUND",
  SUBMISSION_DEADLINE_PASSED: "SUBMISSION_DEADLINE_PASSED",
  SUBMISSION_ALREADY_SUBMITTED: "SUBMISSION_ALREADY_SUBMITTED",
  SUBMISSION_ALREADY_GRADED: "SUBMISSION_ALREADY_GRADED",
  GRADE_OUT_OF_RANGE: "GRADE_OUT_OF_RANGE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_TYPE_INVALID: "FILE_TYPE_INVALID",

  // Lessons (NotFoundError)
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  LESSON_NOT_IN_COURSE: "LESSON_NOT_IN_COURSE",

  // Certificates (NotFoundError o DomainError o AuthorizationError)
  CERTIFICATE_NOT_FOUND: "CERTIFICATE_NOT_FOUND",
  CERTIFICATE_NOT_ELIGIBLE: "CERTIFICATE_NOT_ELIGIBLE",
  CERTIFICATE_ALREADY_ISSUED: "CERTIFICATE_ALREADY_ISSUED",
  CERTIFICATE_REVOKED: "CERTIFICATE_REVOKED",
  AUTHZ_CANNOT_REVOKE_CERTIFICATE: "AUTHZ_CANNOT_REVOKE_CERTIFICATE",
  AUTHZ_CANNOT_VIEW_CERTIFICATE_PDF: "AUTHZ_CANNOT_VIEW_CERTIFICATE_PDF",

  // Academic + corporate certificates (Bloque 22.2)
  ACADEMIC_CERTIFICATE_NOT_FOUND: "ACADEMIC_CERTIFICATE_NOT_FOUND",
  ACADEMIC_CERTIFICATE_ALREADY_EXISTS: "ACADEMIC_CERTIFICATE_ALREADY_EXISTS",
  AUTHZ_CANNOT_MANAGE_ACADEMIC_CERTIFICATES: "AUTHZ_CANNOT_MANAGE_ACADEMIC_CERTIFICATES",
  CORPORATE_CERTIFICATE_NOT_FOUND: "CORPORATE_CERTIFICATE_NOT_FOUND",
  CORPORATE_CERTIFICATE_ALREADY_ISSUED: "CORPORATE_CERTIFICATE_ALREADY_ISSUED",
  CORPORATE_CERTIFICATE_REVOKED: "CORPORATE_CERTIFICATE_REVOKED",
  AUTHZ_CANNOT_ISSUE_CORPORATE_CERTIFICATE: "AUTHZ_CANNOT_ISSUE_CORPORATE_CERTIFICATE",
  AUTHZ_CANNOT_REVOKE_CORPORATE_CERTIFICATE: "AUTHZ_CANNOT_REVOKE_CORPORATE_CERTIFICATE",
  AUTHZ_CANNOT_VIEW_CORPORATE_CERTIFICATE_PDF: "AUTHZ_CANNOT_VIEW_CORPORATE_CERTIFICATE_PDF",

  // AI (InfrastructureError o DomainError dependiendo)
  AI_TIMEOUT: "AI_TIMEOUT",
  AI_PARSE_FAILED: "AI_PARSE_FAILED",
  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  AI_RATE_LIMITED: "AI_RATE_LIMITED",

  // Infrastructure (InfrastructureError, 500)
  DATABASE_ERROR: "DATABASE_ERROR",
  EMAIL_PROVIDER_ERROR: "EMAIL_PROVIDER_ERROR",
  STORAGE_ERROR: "STORAGE_ERROR",

  // Forum (NotFoundError o AuthorizationError)
  FORUM_NOT_FOUND: "FORUM_NOT_FOUND",
  THREAD_NOT_FOUND: "THREAD_NOT_FOUND",
  AUTHZ_CANNOT_POST_IN_FORUM: "AUTHZ_CANNOT_POST_IN_FORUM",
  AUTHZ_CANNOT_EDIT_THREAD: "AUTHZ_CANNOT_EDIT_THREAD",

  // Courses (NotFoundError)
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",

  // Course content editor (Bloque 19)
  MODULE_NOT_FOUND: "MODULE_NOT_FOUND",
  MODULE_HAS_DEPENDENCIES: "MODULE_HAS_DEPENDENCIES",
  MODULE_WEIGHT_SUM_EXCEEDED: "MODULE_WEIGHT_SUM_EXCEEDED",
  MODULE_REORDER_NO_NEIGHBOR: "MODULE_REORDER_NO_NEIGHBOR",
  AUTHZ_CANNOT_EDIT_COURSE_CONTENT: "AUTHZ_CANNOT_EDIT_COURSE_CONTENT",
  LESSON_HAS_DEPENDENCIES: "LESSON_HAS_DEPENDENCIES",
  LESSON_REORDER_NO_NEIGHBOR: "LESSON_REORDER_NO_NEIGHBOR",
  ASSIGNMENT_HAS_DEPENDENCIES: "ASSIGNMENT_HAS_DEPENDENCIES",

  // Course resources (Bloque 20)
  COURSE_RESOURCE_NOT_FOUND: "COURSE_RESOURCE_NOT_FOUND",
  COURSE_STORAGE_QUOTA_EXCEEDED: "COURSE_STORAGE_QUOTA_EXCEEDED",
  FILE_MIME_TYPE_NOT_ALLOWED: "FILE_MIME_TYPE_NOT_ALLOWED",
  AUTHZ_CANNOT_EDIT_COURSE_RESOURCES: "AUTHZ_CANNOT_EDIT_COURSE_RESOURCES",

  // Announcements (NotFoundError o AuthorizationError)
  ANNOUNCEMENT_NOT_FOUND: "ANNOUNCEMENT_NOT_FOUND",
  AUTHZ_CANNOT_EMIT_ANNOUNCEMENT: "AUTHZ_CANNOT_EMIT_ANNOUNCEMENT",

  // Calendar (Bloque 15)
  CALENDAR_EVENT_NOT_FOUND: "CALENDAR_EVENT_NOT_FOUND",
  AUTHZ_CANNOT_VIEW_CALENDAR: "AUTHZ_CANNOT_VIEW_CALENDAR",
  AUTHZ_CANNOT_EDIT_CALENDAR: "AUTHZ_CANNOT_EDIT_CALENDAR",

  // Profile (Bloque 16)
  PROFILE_PASSWORD_INCORRECT: "PROFILE_PASSWORD_INCORRECT",
  // Bloque 22.6: password reuse detectado por Supabase Auth.
  PROFILE_PASSWORD_SAME_AS_CURRENT: "PROFILE_PASSWORD_SAME_AS_CURRENT",

  // Admin user management (AuthorizationError, NotFoundError, DomainError)
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  USER_DELETE_CONFIRMATION_MISMATCH: "USER_DELETE_CONFIRMATION_MISMATCH",
  AUTHZ_CANNOT_MANAGE_USERS: "AUTHZ_CANNOT_MANAGE_USERS",
  AUTHZ_CANNOT_CHANGE_OWN_ROLE: "AUTHZ_CANNOT_CHANGE_OWN_ROLE",
  AUTHZ_CANNOT_TARGET_SELF: "AUTHZ_CANNOT_TARGET_SELF",
  AUTHZ_CANNOT_TARGET_LAST_ADMIN: "AUTHZ_CANNOT_TARGET_LAST_ADMIN",

  // Validation general (ValidationError, 400). SECURITY.md linea 178
  // referencia este code en el ejemplo de createThread action.
  VALIDATION_FAILED: "VALIDATION_FAILED",

  // Rate limiting (AppError con statusCode 429). SECURITY.md linea 562
  // referencia este code en el ejemplo de loginAction.
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
